function outPath = makeOutputFilename(inputFilename, customSuffix, outDir, opts)

% generated by ChatGPT
    arguments
        inputFilename (1,1) string % can be simple baseName
        customSuffix  (1,1) string
        outDir        (1,1) string = ""
        opts.extension (1,1) string = ""
    end

    [~, baseName, ext] = fileparts(inputFilename);
    if(~strcmp(opts.extension, ""))
        ext = opts.extension;
    end
    if(strcmp(ext, ""))
        error("Failed to parse extension, you need to specify it.")
    end

    outFile = baseName + "__" + customSuffix + ext;

    if outDir ~= ""
        outPath = fullfile(outDir, outFile);
    else
        outPath = outFile;
    end

    if exist(outPath, 'file')
        error("Output file already exists: %s", outPath);
    end
end
