function experiment = createExperimentStruct( ...
    errors, ...
    tfaVect,loadConfig,preprocConfig, ...
    pshe,bphe,rc,hre)
arguments
    errors Errors
    tfaVect cell
    loadConfig SignalLoadingConfig
    preprocConfig  PreprocessingConfig
    pshe PhaseStftHearbeatExtractor
    bphe BandPassHeartbeatExtractor
    rc ResultsCombiner
    hre HeartRateComparable
end
% this function creates experiment config and results of
%processing using vitalSignsMethodsPhaser_example script

% supported by ChatGPT
experiment = struct();

experiment.errors = struct( ...
    'methods', {{'pshe','bphe','rc'}}, ...
    'ridgeRMSE', errors.errors_memory_RMSE, ...
    'peaksRMSE', errors.errors_nomemory_RMSE, ...
    'ridgeMAE', errors.errors_memory_MAE, ...
    'peaksMAE', errors.errors_nomemory_MAE ...
);

experiment.tfa = cellfun(@(tfa) struct( ...
    'detectPeaksMethod', tfa.detectPeaksMethod, ...
    'detectRidgeSelectMethod', tfa.detectRidgeSelectMethod, ...
    'Synchrosqueezed', tfa.Synchrosqueezed, ...
    'WindowWidth', tfa.WindowWidth, ...
    'FrequencyResolution', tfa.FrequencyResolution, ...
    'MaximumVisibleFrequency', tfa.MaximumVisibleFrequency, ...
    'detectRidgePossibleLowFrequency', tfa.detectRidgePossibleLowFrequency, ...
    'detectRidgePossibleHighFrequency', tfa.detectRidgePossibleHighFrequency, ...
    'detectRidgeJumpPenalty', tfa.detectRidgeJumpPenalty, ...
    'detectRidgeNuberOfRidges', tfa.detectRidgeNuberOfRidges, ...
    'detectRidgeDesiredNearestFrequency', tfa.detectRidgeDesiredNearestFrequency, ...
    'detectPeaksExactDistance', tfa.detectPeaksExactDistance, ...
    'detectPeaksDistanceTolerance', tfa.detectPeaksDistanceTolerance ...
), tfaVect, 'UniformOutput', false);

experiment.loading = struct( ...
    'lengthSeconds', loadConfig.lengthSeconds, ...
    'offsetSeconds', loadConfig.offsetSeconds, ...
    'filename', loadConfig.filename ...
);

experiment.preprocessing = struct( ...
    'range_cell', preprocConfig.range_cell, ...
    'fast_time_data_start', preprocConfig.fast_time_data_start, ...
    'fast_time_data_end', preprocConfig.fast_time_data_end, ...
    'FastTimeWindow', preprocConfig.FastTimeWindow, ...
    'phaseUnwrappingMethod', preprocConfig.phaseUnwrappingMethod, ...
    'phaseDiscontCompParams', preprocConfig.phaseDiscontCompParams, ...
    "rangeCellAutoSelectionWindow", preprocConfig.rangeCellAutoSelectionWindow ...
);

experiment.pshe = struct( ...
    'desiredTimeRes', pshe.desiredTimeRes, ...
    'windowWidth', pshe.windowWidth, ...
    'frequencyResolution', pshe.frequencyResolution, ...
    'maximumVisibleFrequency', pshe.maximumVisibleFrequency, ...
    'heartOscillationFreqRange', pshe.heartOscillationFreqRange, ...
    'phaseCutoffFreqLow', pshe.phaseCutoffFreqLow, ...
    'resultCutoffFreqLow', pshe.resultCutoffFreqLow ...
);

experiment.pshe.prediction = struct( ...
    'ErosePartLeft', pshe.ErosePartLeft, ...
    'ErosePartRight', pshe.ErosePartRight, ...
    'furtherAnalysisOutput', pshe.furtherAnalysisOutput, ...
    'PartConsidered', pshe.PartConsidered ...
);

experiment.bphe = struct( ...
    'PassBand', bphe.PassBand, ...
    'UpsamplingFactor', bphe.UpsamplingFactor ...
);

experiment.bphe.prediction = struct( ...
    'ErosePartLeft', bphe.ErosePartLeft, ...
    'ErosePartRight', bphe.ErosePartRight, ...
    'furtherAnalysisOutput', bphe.furtherAnalysisOutput, ...
    'PartConsidered', bphe.PartConsidered ...
);


experiment.rc.input = struct( ...
    'weight1', rc.weight1, ...
    'weight2', rc.weight2, ...
    'timeDelay2', rc.timeDelay2, ...
    'estimateDelay', rc.estimateDelay, ...
    'estimateSign', rc.estimateSign ...
);

experiment.rc.prediction = struct( ...
    'ErosePartLeft', rc.ErosePartLeft, ...
    'ErosePartRight', rc.ErosePartRight, ...
    'furtherAnalysisOutput', rc.furtherAnalysisOutput, ...
    'PartConsidered', rc.PartConsidered ...
);



experiment.rc.adjustment = struct( ...
    'windowWidth', rc.windowWidth, ...
    'windowStep', rc.windowStep, ...
    'maxAllowableShift', rc.maxAllowableShift ...
);



experiment.hre = struct( ...
    'path', hre.path, ...
    'ManualTimeShift',string(hre.ManualTimeShift, "hh:mm:ss") ...
);


end


