function cfg = readConfigDemorad(filename)
% GENERATED BY CHATGPT
% READCONFIG Wczytuje konfigurację z pliku tekstowego.
%   cfg = READCONFIG(filename)
%
% Oczekiwany format pliku:
%   Started at <data/czas>
%   PRF = <wartość> Hz
%   Bandwidth = <wartość> Hz
%   Carrier = <wartość> Hz
%   Length = <wartość> s
%   Comments:
%   <wiele linii komentarza>

    fid = fopen(filename, 'r');
    if fid == -1
        error('Nie można otworzyć pliku: %s', filename);
    end

    cfg = struct();
    inComments = false;
    commentLines = {};

    while ~feof(fid)
        line = strtrim(fgetl(fid));
        if isempty(line)
            continue;
        end

        % Sprawdzenie sekcji komentarzy
        if strcmpi(line, 'Comments:')
            inComments = true;
            continue;
        end

        if inComments
            % Wszystko po "Comments:" traktujemy jako komentarz
            commentLines{end+1} = line; %#ok<AGROW>
            continue;
        end

        % Parsowanie standardowych pól klucz = wartość
        tokens = regexp(line, '^(.*?)\s*=\s*(.*?)$', 'tokens');
        if ~isempty(tokens)
            key = strtrim(tokens{1}{1});
            val = strtrim(tokens{1}{2});

            % Usuwamy jednostki i konwertujemy na liczbę, jeśli się da
            valNum = sscanf(val, '%f');
            if ~isempty(valNum)
                cfg.(sanitizeField(key)) = valNum;
            else
                cfg.(sanitizeField(key)) = val;
            end
        else
            % Możliwe pole "Started at ..."
            if startsWith(line, 'Started at')
                cfg.StartedAt = strtrim(strrep(line, 'Started at', ''));
            end
        end
    end

    fclose(fid);

    % Dodanie komentarzy
    cfg.Comments = strjoin(commentLines, newline);
    cfg.SamplingFreq = 1e6; % Hz
end

function f = sanitizeField(str)
% Zamienia nazwę pola na zgodną z wymaganiami MATLABa
    f = regexprep(str, '\s+', '_');    % spacje → podkreślniki
    f = regexprep(f, '[^a-zA-Z0-9_]', ''); % usunięcie niedozwolonych znaków
end
